name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - '**/README.md'
      - '**/VERSION'
      - '**/.gitignore'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-8
    - name: make check
      run: bash install.sh -c -g
