name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - '**/README.md'
      - '**/VERSION'
      - '**/.gitignore'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.6.0-devel-ubuntu24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y cmake git build-essential
      - name: Clone cuarena
        run: git clone https://github.com/muhos/cuArena.git $HOME/cuarena
      - name: Build
        run: bash install.sh -c -g
